/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicExpertsIndexRouteImport } from './routes/_public/experts/index'
import { Route as PublicExpertsExpertIdRouteImport } from './routes/_public/experts/$expertId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicExpertsIndexRoute = PublicExpertsIndexRouteImport.update({
  id: '/_public/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicExpertsExpertIdRoute = PublicExpertsExpertIdRouteImport.update({
  id: '/_public/experts/$expertId',
  path: '/experts/$expertId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/experts/$expertId': typeof PublicExpertsExpertIdRoute
  '/experts': typeof PublicExpertsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/experts/$expertId': typeof PublicExpertsExpertIdRoute
  '/experts': typeof PublicExpertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_public/experts/$expertId': typeof PublicExpertsExpertIdRoute
  '/_public/experts/': typeof PublicExpertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/experts/$expertId' | '/experts'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/experts/$expertId' | '/experts'
  id: '__root__' | '/_auth' | '/_auth/login' | '/_app/' | '/_public/experts/$expertId' | '/_public/experts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  PublicExpertsExpertIdRoute: typeof PublicExpertsExpertIdRoute
  PublicExpertsIndexRoute: typeof PublicExpertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/experts/': {
      id: '/_public/experts/'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof PublicExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/experts/$expertId': {
      id: '/_public/experts/$expertId'
      path: '/experts/$expertId'
      fullPath: '/experts/$expertId'
      preLoaderRoute: typeof PublicExpertsExpertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  PublicExpertsExpertIdRoute: PublicExpertsExpertIdRoute,
  PublicExpertsIndexRoute: PublicExpertsIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
