/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicExpertsIndexRouteImport } from './routes/_public/experts/index'
import { Route as PublicBookingsBookingIdRouteImport } from './routes/_public/bookings/$bookingId'
import { Route as PublicExpertsExpertSlugIndexRouteImport } from './routes/_public/experts/$expertSlug/index'
import { Route as PublicExpertsExpertSlugServiceSlugRouteImport } from './routes/_public/experts/$expertSlug/$serviceSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicExpertsIndexRoute = PublicExpertsIndexRouteImport.update({
  id: '/_public/experts/',
  path: '/experts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicBookingsBookingIdRoute = PublicBookingsBookingIdRouteImport.update({
  id: '/_public/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicExpertsExpertSlugIndexRoute = PublicExpertsExpertSlugIndexRouteImport.update({
  id: '/_public/experts/$expertSlug/',
  path: '/experts/$expertSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicExpertsExpertSlugServiceSlugRoute = PublicExpertsExpertSlugServiceSlugRouteImport.update({
  id: '/_public/experts/$expertSlug/$serviceSlug',
  path: '/experts/$expertSlug/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/bookings/$bookingId': typeof PublicBookingsBookingIdRoute
  '/experts': typeof PublicExpertsIndexRoute
  '/experts/$expertSlug/$serviceSlug': typeof PublicExpertsExpertSlugServiceSlugRoute
  '/experts/$expertSlug': typeof PublicExpertsExpertSlugIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/bookings/$bookingId': typeof PublicBookingsBookingIdRoute
  '/experts': typeof PublicExpertsIndexRoute
  '/experts/$expertSlug/$serviceSlug': typeof PublicExpertsExpertSlugServiceSlugRoute
  '/experts/$expertSlug': typeof PublicExpertsExpertSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_public/bookings/$bookingId': typeof PublicBookingsBookingIdRoute
  '/_public/experts/': typeof PublicExpertsIndexRoute
  '/_public/experts/$expertSlug/$serviceSlug': typeof PublicExpertsExpertSlugServiceSlugRoute
  '/_public/experts/$expertSlug/': typeof PublicExpertsExpertSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/bookings/$bookingId'
    | '/experts'
    | '/experts/$expertSlug/$serviceSlug'
    | '/experts/$expertSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/bookings/$bookingId'
    | '/experts'
    | '/experts/$expertSlug/$serviceSlug'
    | '/experts/$expertSlug'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/login'
    | '/_app/'
    | '/_public/bookings/$bookingId'
    | '/_public/experts/'
    | '/_public/experts/$expertSlug/$serviceSlug'
    | '/_public/experts/$expertSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  PublicBookingsBookingIdRoute: typeof PublicBookingsBookingIdRoute
  PublicExpertsIndexRoute: typeof PublicExpertsIndexRoute
  PublicExpertsExpertSlugServiceSlugRoute: typeof PublicExpertsExpertSlugServiceSlugRoute
  PublicExpertsExpertSlugIndexRoute: typeof PublicExpertsExpertSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/experts/': {
      id: '/_public/experts/'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof PublicExpertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/bookings/$bookingId': {
      id: '/_public/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof PublicBookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/experts/$expertSlug/': {
      id: '/_public/experts/$expertSlug/'
      path: '/experts/$expertSlug'
      fullPath: '/experts/$expertSlug'
      preLoaderRoute: typeof PublicExpertsExpertSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/experts/$expertSlug/$serviceSlug': {
      id: '/_public/experts/$expertSlug/$serviceSlug'
      path: '/experts/$expertSlug/$serviceSlug'
      fullPath: '/experts/$expertSlug/$serviceSlug'
      preLoaderRoute: typeof PublicExpertsExpertSlugServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  PublicBookingsBookingIdRoute: PublicBookingsBookingIdRoute,
  PublicExpertsIndexRoute: PublicExpertsIndexRoute,
  PublicExpertsExpertSlugServiceSlugRoute: PublicExpertsExpertSlugServiceSlugRoute,
  PublicExpertsExpertSlugIndexRoute: PublicExpertsExpertSlugIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
