/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_PUBLIC_API_BASE_URL: string
  readonly VITE_PUBLIC_BASE_PATH: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}