/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    PmcHonoServer: {
      name: string;
      type: "sst.aws.Function";
      url: string;
    };
    PmcPortal: {
      type: "sst.aws.StaticSite";
      url: string;
    };
    PmcRouter: {
      type: "sst.aws.Router";
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import "sst";
export {};
