/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blog: Blog;
    experts: Expert;
    'contact-submissions': ContactSubmission;
    'team-members': TeamMember;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    experts: ExpertsSelect<false> | ExpertsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    home: Home;
    'deep-tms': DeepTm;
    'contact-us': ContactUs;
    'about-us': AboutUs;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'deep-tms': DeepTmsSelect<false> | DeepTmsSelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  author: string;
  image?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: string;
  expertName: string;
  image?: (string | null) | Media;
  profession: string;
  headline?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  address: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  memberName: string;
  image: string | Media;
  role: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'experts';
        value: string | Expert;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  image?: T;
  content?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  expertName?: T;
  image?: T;
  profession?: T;
  headline?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  address?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  memberName?: T;
  image?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  heroSetion?: {
    heroSectionTitle?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    heroSectionDescription?: string | null;
    heroSectionImage?: (string | null) | Media;
    heroSectionAction?: string | null;
    heroSectionHeadline?: string | null;
    heroSectionDetails?:
      | {
          label?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  deepTmsSection?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    action?: string | null;
    deepTmsFeatures?:
      | {
          title?: string | null;
          background?: ('primary' | 'accent') | null;
          image?: (string | null) | Media;
          description?: string | null;
          stampImage?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  treatmentSection?: {
    title?: string | null;
    premaryImage?: (string | null) | Media;
    secondryImage?: (string | null) | Media;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    subTitle?: string | null;
    action?: string | null;
    featureList?:
      | {
          title?: string | null;
          feature?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseSection?: {
    title?: string | null;
    action?: string | null;
    image?: (string | null) | Media;
    featuresCards?:
      | {
          featureTitle?: string | null;
          featureDescription?: string | null;
          featureIcon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  packagesSection?: {
    title?: string | null;
    availablePackages?:
      | {
          name?: string | null;
          price?: {
            price?: string | null;
            unitText?: string | null;
          };
          description?: string | null;
          featureHeadline?: string | null;
          features?:
            | {
                title?: string | null;
                id?: string | null;
              }[]
            | null;
          action?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  appointmentSection?: {
    appointmentSection?: {
      title?: string | null;
      contacts?:
        | {
            phone?: string | null;
            id?: string | null;
          }[]
        | null;
      location?: string | null;
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  testimonialSection?: {
    title?: string | null;
    testimonialSlides?:
      | {
          image?: (string | null) | Media;
          title?: string | null;
          quote?: string | null;
          quoteAuthor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    title?: string | null;
    faqQuestionsAndAnswer?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  expertsSection?: {
    title?: string | null;
    experts?: (string | Expert)[] | null;
    action?: string | null;
  };
  blogsSection?: {
    title?: string | null;
    action?: string | null;
    featuredBlogs?: (string | Blog)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-tms".
 */
export interface DeepTm {
  id: string;
  deepTmsHeroSection?: {
    title?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (string | null) | Media;
    statCards?:
      | {
          title?: string | null;
          value?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  deepTmsWorkSection?: {
    title?: string | null;
    deepTmsWorkCards?:
      | {
          image?: (string | null) | Media;
          title?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  deepTmsComparisonSection?: {
    title?: string | null;
    featureParameterColumn?: {
      heading?: string | null;
      background?: ('card' | 'card-foreground') | null;
      textColor?: ('primary' | 'primary-foreground') | null;
    };
    deepTmsFeatureColumn?: {
      heading?: string | null;
      background?: ('card' | 'card-foreground') | null;
      textColor?: ('primary' | 'primary-foreground') | null;
    };
    traditionalFeatureColumn?: {
      heading?: string | null;
      background?: ('card' | 'card-foreground') | null;
      textColor?: ('primary' | 'primary-foreground') | null;
    };
    comparisonRows?:
      | {
          feature?: string | null;
          deepTmsFeature?: string | null;
          traditionalFeature?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  deepTmsEligibilitySection?: {
    title?: string | null;
    image?: (string | null) | Media;
    subTitle?: string | null;
    eligibilityList?:
      | {
          addEligibility?: string | null;
          id?: string | null;
        }[]
      | null;
    action?: string | null;
  };
  appointmentSection?: {
    appointmentSection?: {
      title?: string | null;
      contacts?:
        | {
            phone?: string | null;
            id?: string | null;
          }[]
        | null;
      location?: string | null;
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  faqSection?: {
    title?: string | null;
    faqQuestionsAndAnswer?:
      | {
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: string;
  contactUs?: {
    title?: string | null;
    subtitle?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: string;
  aboutUsHeroSection?: {
    preHeader?: string | null;
    heading?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    overlayContent?: {
      overlayImage?: (string | null) | Media;
      heading?: string | null;
      description?: string | null;
      statistics?:
        | {
            value?: string | null;
            label?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  whatWeDoSection: {
    heading: string;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * The two cards that appear on the left and right of the image.
     */
    featureCards?:
      | {
          heading?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  missionVisionStory?: {
    purposeHeading?: string | null;
    mission?: {
      heading?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    vision?: {
      heading?: string | null;
      description?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    storyIntro?: string | null;
    storyContent?: {
      heading?: string | null;
      story?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
  };
  teamMembersSection?: {
    title?: string | null;
    members?: (string | TeamMember)[] | null;
  };
  expertsSection?: {
    title?: string | null;
    experts?: (string | Expert)[] | null;
    action?: string | null;
  };
  opportunitiesSection?: {
    title?: string | null;
    image?: (string | null) | Media;
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    action?: string | null;
    subAction?: string | null;
  };
  appointmentSection?: {
    appointmentSection?: {
      title?: string | null;
      contacts?:
        | {
            phone?: string | null;
            id?: string | null;
          }[]
        | null;
      location?: string | null;
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSetion?:
    | T
    | {
        heroSectionTitle?: T;
        heroSectionDescription?: T;
        heroSectionImage?: T;
        heroSectionAction?: T;
        heroSectionHeadline?: T;
        heroSectionDetails?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  deepTmsSection?:
    | T
    | {
        title?: T;
        description?: T;
        action?: T;
        deepTmsFeatures?:
          | T
          | {
              title?: T;
              background?: T;
              image?: T;
              description?: T;
              stampImage?: T;
              id?: T;
            };
      };
  treatmentSection?:
    | T
    | {
        title?: T;
        premaryImage?: T;
        secondryImage?: T;
        description?: T;
        subTitle?: T;
        action?: T;
        featureList?:
          | T
          | {
              title?: T;
              feature?: T;
              id?: T;
            };
      };
  whyChooseSection?:
    | T
    | {
        title?: T;
        action?: T;
        image?: T;
        featuresCards?:
          | T
          | {
              featureTitle?: T;
              featureDescription?: T;
              featureIcon?: T;
              id?: T;
            };
      };
  packagesSection?:
    | T
    | {
        title?: T;
        availablePackages?:
          | T
          | {
              name?: T;
              price?:
                | T
                | {
                    price?: T;
                    unitText?: T;
                  };
              description?: T;
              featureHeadline?: T;
              features?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
              action?: T;
              id?: T;
            };
      };
  appointmentSection?:
    | T
    | {
        appointmentSection?:
          | T
          | {
              title?: T;
              contacts?:
                | T
                | {
                    phone?: T;
                    id?: T;
                  };
              location?: T;
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T;
                    url?: T;
                    id?: T;
                  };
            };
      };
  testimonialSection?:
    | T
    | {
        title?: T;
        testimonialSlides?:
          | T
          | {
              image?: T;
              title?: T;
              quote?: T;
              quoteAuthor?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        title?: T;
        faqQuestionsAndAnswer?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  expertsSection?:
    | T
    | {
        title?: T;
        experts?: T;
        action?: T;
      };
  blogsSection?:
    | T
    | {
        title?: T;
        action?: T;
        featuredBlogs?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-tms_select".
 */
export interface DeepTmsSelect<T extends boolean = true> {
  deepTmsHeroSection?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        statCards?:
          | T
          | {
              title?: T;
              value?: T;
              description?: T;
              id?: T;
            };
      };
  deepTmsWorkSection?:
    | T
    | {
        title?: T;
        deepTmsWorkCards?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  deepTmsComparisonSection?:
    | T
    | {
        title?: T;
        featureParameterColumn?:
          | T
          | {
              heading?: T;
              background?: T;
              textColor?: T;
            };
        deepTmsFeatureColumn?:
          | T
          | {
              heading?: T;
              background?: T;
              textColor?: T;
            };
        traditionalFeatureColumn?:
          | T
          | {
              heading?: T;
              background?: T;
              textColor?: T;
            };
        comparisonRows?:
          | T
          | {
              feature?: T;
              deepTmsFeature?: T;
              traditionalFeature?: T;
              id?: T;
            };
      };
  deepTmsEligibilitySection?:
    | T
    | {
        title?: T;
        image?: T;
        subTitle?: T;
        eligibilityList?:
          | T
          | {
              addEligibility?: T;
              id?: T;
            };
        action?: T;
      };
  appointmentSection?:
    | T
    | {
        appointmentSection?:
          | T
          | {
              title?: T;
              contacts?:
                | T
                | {
                    phone?: T;
                    id?: T;
                  };
              location?: T;
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T;
                    url?: T;
                    id?: T;
                  };
            };
      };
  faqSection?:
    | T
    | {
        title?: T;
        faqQuestionsAndAnswer?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  contactUs?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  aboutUsHeroSection?:
    | T
    | {
        preHeader?: T;
        heading?: T;
        description?: T;
        overlayContent?:
          | T
          | {
              overlayImage?: T;
              heading?: T;
              description?: T;
              statistics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
      };
  whatWeDoSection?:
    | T
    | {
        heading?: T;
        description?: T;
        featureCards?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  missionVisionStory?:
    | T
    | {
        purposeHeading?: T;
        mission?:
          | T
          | {
              heading?: T;
              description?: T;
            };
        vision?:
          | T
          | {
              heading?: T;
              description?: T;
            };
        storyIntro?: T;
        storyContent?:
          | T
          | {
              heading?: T;
              story?: T;
            };
      };
  teamMembersSection?:
    | T
    | {
        title?: T;
        members?: T;
      };
  expertsSection?:
    | T
    | {
        title?: T;
        experts?: T;
        action?: T;
      };
  opportunitiesSection?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        action?: T;
        subAction?: T;
      };
  appointmentSection?:
    | T
    | {
        appointmentSection?:
          | T
          | {
              title?: T;
              contacts?:
                | T
                | {
                    phone?: T;
                    id?: T;
                  };
              location?: T;
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T;
                    url?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}