/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    blog: Blog
    experts: Expert
    'team-members': TeamMember
    testimonial: Testimonial
    services: Service
    leads: Lead
    appointments: Appointment
    webinars: Webinar
    quiz: Quiz
    internships: Internship
    exports: Export
    'payload-jobs': PayloadJob
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    services: {
      subservices: 'services'
    }
  }
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    blog: BlogSelect<false> | BlogSelect<true>
    experts: ExpertsSelect<false> | ExpertsSelect<true>
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>
    testimonial: TestimonialSelect<false> | TestimonialSelect<true>
    services: ServicesSelect<false> | ServicesSelect<true>
    leads: LeadsSelect<false> | LeadsSelect<true>
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>
    webinars: WebinarsSelect<false> | WebinarsSelect<true>
    quiz: QuizSelect<false> | QuizSelect<true>
    internships: InternshipsSelect<false> | InternshipsSelect<true>
    exports: ExportsSelect<false> | ExportsSelect<true>
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  globals: {
    home: Home
    'deep-tms': DeepTm
    'our-services': OurService
    'contact-us': ContactUs
    'about-us': AboutUs
    'privacy-policy': PrivacyPolicy
    'terms-and-conditions': TermsAndCondition
    'our-blogs': OurBlog
    'quiz-page': QuizPage
  }
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>
    'deep-tms': DeepTmsSelect<false> | DeepTmsSelect<true>
    'our-services': OurServicesSelect<false> | OurServicesSelect<true>
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>
    'terms-and-conditions': TermsAndConditionsSelect<false> | TermsAndConditionsSelect<true>
    'our-blogs': OurBlogsSelect<false> | OurBlogsSelect<true>
    'quiz-page': QuizPageSelect<false> | QuizPageSelect<true>
  }
  locale: null
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport
      inline: {
        input: unknown
        output: unknown
      }
    }
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string
  title: string
  slug: string
  author: string
  category: (string | Service)[]
  image?: (string | null) | Media
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  publishedAt: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string
  _order?: string | null
  name: string
  slug: string
  image?: (string | null) | Media
  /**
   * Leave empty for Main Service.
   */
  parent?: (string | null) | Service
  description?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  isActive?: boolean | null
  subservices?: {
    docs?: (string | Service)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts".
 */
export interface Expert {
  id: string
  expertName: string
  image?: (string | null) | Media
  profession: 'Psychologist' | 'Psychiatrist'
  headline?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  experties?: (string | Service)[] | null
  minimumFee?: number | null
  /**
   * Duration in minutes
   */
  sessionDuration?: number | null
  /**
   * Calendly or other booking link
   */
  bookingLink?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string
  memberName: string
  image: string | Media
  role: string
  bio: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial".
 */
export interface Testimonial {
  id: string
  type?: ('text' | 'video') | null
  authorName: string
  auhtorImage?: (string | null) | Media
  title?: string | null
  message?: string | null
  /**
   * YouTub video link
   */
  videoUrl?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string
  fullName: string
  email?: string | null
  phone: string
  service?: (string | null) | Service
  subService?: (string | null) | Service
  message?: string | null
  source?: ('facebook' | 'instagram' | 'linkedin' | 'website' | 'clinic' | 'referral' | 'ads' | 'other')[] | null
  status?: ('new' | 'contacted' | 'followUp' | 'interested' | 'converted' | 'lost') | null
  leadLevel?: ('hot' | 'warm' | 'cold') | null
  updatedAt: string
  createdAt: string
}
/**
 * These are trial session appointments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string
  fullName: string
  phone: string
  email?: string | null
  service?: (string | null) | Service
  subService?: (string | null) | Service
  message?: string | null
  dateTime: string
  /**
   * Amount in INR
   */
  amount: number
  paymentStatus: 'unpaid' | 'pending' | 'paid' | 'failed'
  /**
   * Order ID from payment gateway
   */
  orderId?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: string
  title: string
  date: string
  speaker?: {
    name?: string | null
    image?: (string | null) | Media
    profession?: string | null
  }
  poster?: (string | null) | Media
  videoLink?: string | null
  description?: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  slug: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz".
 */
export interface Quiz {
  id: string
  _order?: string | null
  title: string
  image: string | Media
  /**
   * Auto-generated from title (e.g., /quiz/anxiety-quiz)
   */
  slug: string
  /**
   * Shown at the top of the quiz page
   */
  description?: string | null
  questionnaire: {
    question: string
    options: {
      /**
       * e.g., "a", "b", "c"
       */
      value: string
      /**
       * e.g., "Not at all", "Sometimes"
       */
      label: string
      /**
       * Points awarded for this option
       */
      score: number
      id?: string | null
    }[]
    id?: string | null
  }[]
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internships".
 */
export interface Internship {
  id: string
  fullName: string
  email: string
  phoneNumber?: string | null
  schoolOrUniversity?: string | null
  degreeOrProgram?: string | null
  interestedIn: string
  message?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string
  name?: string | null
  format?: ('csv' | 'json') | null
  limit?: number | null
  page?: number | null
  sort?: string | null
  sortOrder?: ('asc' | 'desc') | null
  drafts?: ('yes' | 'no') | null
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null
  fields?: string[] | null
  collectionSlug: string
  where?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  taskStatus?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  completedAt?: string | null
  totalTried?: number | null
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string
        completedAt: string
        taskSlug: 'inline' | 'createCollectionExport'
        taskID: string
        input?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        output?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        state: 'failed' | 'succeeded'
        error?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        id?: string | null
      }[]
    | null
  taskSlug?: ('inline' | 'createCollectionExport') | null
  queue?: string | null
  waitUntil?: string | null
  processing?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'blog'
        value: string | Blog
      } | null)
    | ({
        relationTo: 'experts'
        value: string | Expert
      } | null)
    | ({
        relationTo: 'team-members'
        value: string | TeamMember
      } | null)
    | ({
        relationTo: 'testimonial'
        value: string | Testimonial
      } | null)
    | ({
        relationTo: 'services'
        value: string | Service
      } | null)
    | ({
        relationTo: 'leads'
        value: string | Lead
      } | null)
    | ({
        relationTo: 'appointments'
        value: string | Appointment
      } | null)
    | ({
        relationTo: 'webinars'
        value: string | Webinar
      } | null)
    | ({
        relationTo: 'quiz'
        value: string | Quiz
      } | null)
    | ({
        relationTo: 'internships'
        value: string | Internship
      } | null)
    | ({
        relationTo: 'exports'
        value: string | Export
      } | null)
    | ({
        relationTo: 'payload-jobs'
        value: string | PayloadJob
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T
  slug?: T
  author?: T
  category?: T
  image?: T
  content?: T
  publishedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experts_select".
 */
export interface ExpertsSelect<T extends boolean = true> {
  expertName?: T
  image?: T
  profession?: T
  headline?: T
  experties?: T
  minimumFee?: T
  sessionDuration?: T
  bookingLink?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  memberName?: T
  image?: T
  role?: T
  bio?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial_select".
 */
export interface TestimonialSelect<T extends boolean = true> {
  type?: T
  authorName?: T
  auhtorImage?: T
  title?: T
  message?: T
  videoUrl?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T
  name?: T
  slug?: T
  image?: T
  parent?: T
  description?: T
  isActive?: T
  subservices?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  fullName?: T
  email?: T
  phone?: T
  service?: T
  subService?: T
  message?: T
  source?: T
  status?: T
  leadLevel?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  fullName?: T
  phone?: T
  email?: T
  service?: T
  subService?: T
  message?: T
  dateTime?: T
  amount?: T
  paymentStatus?: T
  orderId?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  title?: T
  date?: T
  speaker?:
    | T
    | {
        name?: T
        image?: T
        profession?: T
      }
  poster?: T
  videoLink?: T
  description?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz_select".
 */
export interface QuizSelect<T extends boolean = true> {
  _order?: T
  title?: T
  image?: T
  slug?: T
  description?: T
  questionnaire?:
    | T
    | {
        question?: T
        options?:
          | T
          | {
              value?: T
              label?: T
              score?: T
              id?: T
            }
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internships_select".
 */
export interface InternshipsSelect<T extends boolean = true> {
  fullName?: T
  email?: T
  phoneNumber?: T
  schoolOrUniversity?: T
  degreeOrProgram?: T
  interestedIn?: T
  message?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T
  format?: T
  limit?: T
  page?: T
  sort?: T
  sortOrder?: T
  drafts?: T
  selectionToUse?: T
  fields?: T
  collectionSlug?: T
  where?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T
  taskStatus?: T
  completedAt?: T
  totalTried?: T
  hasError?: T
  error?: T
  log?:
    | T
    | {
        executedAt?: T
        completedAt?: T
        taskSlug?: T
        taskID?: T
        input?: T
        output?: T
        state?: T
        error?: T
        id?: T
      }
  taskSlug?: T
  queue?: T
  waitUntil?: T
  processing?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string
  heroSetion?: {
    heroSectionTitle?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    heroSectionDescription?: string | null
    heroSectionImage?: (string | null) | Media
    heroSectionAction?: string | null
    heroSectionHeadline?: string | null
    heroSectionDetails?:
      | {
          label?: string | null
          value?: string | null
          id?: string | null
        }[]
      | null
  }
  deepTmsSection?: {
    title?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    action?: string | null
    deepTmsFeatures?:
      | {
          title?: string | null
          background?: ('primary' | 'accent') | null
          image?: (string | null) | Media
          description?: string | null
          stampImage?: (string | null) | Media
          id?: string | null
        }[]
      | null
  }
  mapSection?: {
    title?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    image?: (string | null) | Media
  }
  treatmentSection?: {
    title?: string | null
    premaryImage?: (string | null) | Media
    secondryImage?: (string | null) | Media
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    subTitle?: string | null
    action?: string | null
    featureList?:
      | {
          title?: string | null
          feature?: string | null
          id?: string | null
        }[]
      | null
    videoUrl?: string | null
  }
  whyChooseSection?: {
    title?: string | null
    action?: string | null
    image?: (string | null) | Media
    featuresCards?:
      | {
          featureTitle?: string | null
          featureDescription?: string | null
          featureIcon?: (string | null) | Media
          id?: string | null
        }[]
      | null
  }
  packagesSection?: {
    title?: string | null
    availablePackages?:
      | {
          name?: string | null
          price?: {
            price?: string | null
            unitText?: string | null
          }
          description?: string | null
          featureHeadline?: string | null
          features?:
            | {
                title?: string | null
                id?: string | null
              }[]
            | null
          action?: string | null
          id?: string | null
        }[]
      | null
  }
  servicesSection?: {
    title?: string | null
    action?: string | null
    cardAction?: string | null
  }
  expertsSection?: {
    title?: string | null
    experts?: (string | Expert)[] | null
    action?: string | null
  }
  contactSection?: {
    contactSection?: {
      title?: string | null
      contacts?:
        | {
            phone?: string | null
            id?: string | null
          }[]
        | null
      location?: string | null
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null
            url?: string | null
            id?: string | null
          }[]
        | null
    }
  }
  quizSection: {
    quizTitle: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    }
    quizDescription: string
    quizFeatures?:
      | {
          text: string
          id?: string | null
        }[]
      | null
    quizButtonText?: string | null
    quizImage?: (string | null) | Media
  }
  testimonialSection?: {
    title?: string | null
    testimonialSlides?: (string | Testimonial)[] | null
  }
  faqSection?: {
    title?: string | null
    faqQuestionsAndAnswer?:
      | {
          question?: string | null
          answer?: string | null
          id?: string | null
        }[]
      | null
  }
  achievementSection?: {
    title?: string | null
    achievements?:
      | {
          number?: string | null
          label?: string | null
          icon?: (string | null) | Media
          id?: string | null
        }[]
      | null
  }
  partnersSection: {
    title: string
    partners?:
      | {
          logo: string | Media
          id?: string | null
        }[]
      | null
  }
  blogsSection?: {
    title?: string | null
    action?: string | null
    featuredBlogs?: (string | Blog)[] | null
  }
  webinarsSection?: {
    title?: string | null
    description?: string | null
    action?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-tms".
 */
export interface DeepTm {
  id: string
  deepTmsHeroSection?: {
    title?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    image?: (string | null) | Media
    videoUrl?: string | null
    statCards?:
      | {
          title?: string | null
          value?: string | null
          description?: string | null
          id?: string | null
        }[]
      | null
    action?: string | null
  }
  deepTmsWorkSection?: {
    title?: string | null
    deepTmsWorkCards?:
      | {
          image?: (string | null) | Media
          title?: string | null
          description?: {
            root: {
              type: string
              children: {
                type: string
                version: number
                [k: string]: unknown
              }[]
              direction: ('ltr' | 'rtl') | null
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
              indent: number
              version: number
            }
            [k: string]: unknown
          } | null
          id?: string | null
        }[]
      | null
  }
  deepTmsComparisonSection?: {
    title?: string | null
    featureParameterColumn?: {
      heading?: string | null
      background?: ('card' | 'card-foreground') | null
      textColor?: ('primary' | 'primary-foreground') | null
    }
    deepTmsFeatureColumn?: {
      heading?: string | null
      background?: ('card' | 'card-foreground') | null
      textColor?: ('primary' | 'primary-foreground') | null
    }
    traditionalFeatureColumn?: {
      heading?: string | null
      background?: ('card' | 'card-foreground') | null
      textColor?: ('primary' | 'primary-foreground') | null
    }
    comparisonRows?:
      | {
          feature?: string | null
          deepTmsFeature?: string | null
          traditionalFeature?: string | null
          id?: string | null
        }[]
      | null
  }
  deepTmsEligibilitySection?: {
    title?: string | null
    image?: (string | null) | Media
    subTitle?: string | null
    eligibilityList?:
      | {
          addEligibility?: string | null
          id?: string | null
        }[]
      | null
    action?: string | null
  }
  servicesSection?: {
    title?: string | null
    action?: string | null
    cardAction?: string | null
  }
  contactSection?: {
    contactSection?: {
      title?: string | null
      contacts?:
        | {
            phone?: string | null
            id?: string | null
          }[]
        | null
      location?: string | null
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null
            url?: string | null
            id?: string | null
          }[]
        | null
    }
  }
  faqSection?: {
    title?: string | null
    faqQuestionsAndAnswer?:
      | {
          question?: string | null
          answer?: string | null
          id?: string | null
        }[]
      | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-services".
 */
export interface OurService {
  id: string
  servicesHeroSection?: {
    image?: (string | null) | Media
    title?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    action?: string | null
    featureCards?:
      | {
          title?: string | null
          description?: string | null
          featureImage?: (string | null) | Media
          id?: string | null
        }[]
      | null
  }
  mainServicesSection?: {
    heading?: string | null
    action?: string | null
  }
  testimonialSection?: {
    title?: string | null
    testimonialSlides?: (string | Testimonial)[] | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: string
  contactUs?: {
    title?: string | null
    subtitle?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: string
  aboutUsHeroSection?: {
    preHeader?: string | null
    heading?: string | null
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    overlayContent?: {
      overlayImage?: (string | null) | Media
      heading?: string | null
      description?: string | null
      statistics?:
        | {
            value?: string | null
            label?: string | null
            id?: string | null
          }[]
        | null
    }
  }
  whatWeDoSection: {
    heading: string
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    /**
     * The two cards that appear on the left and right of the image.
     */
    featureCards?:
      | {
          heading?: string | null
          description?: {
            root: {
              type: string
              children: {
                type: string
                version: number
                [k: string]: unknown
              }[]
              direction: ('ltr' | 'rtl') | null
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
              indent: number
              version: number
            }
            [k: string]: unknown
          } | null
          image?: (string | null) | Media
          id?: string | null
        }[]
      | null
  }
  missionVisionStory?: {
    purposeHeading?: string | null
    mission?: {
      heading?: string | null
      description?: {
        root: {
          type: string
          children: {
            type: string
            version: number
            [k: string]: unknown
          }[]
          direction: ('ltr' | 'rtl') | null
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
          indent: number
          version: number
        }
        [k: string]: unknown
      } | null
    }
    vision?: {
      heading?: string | null
      description?: {
        root: {
          type: string
          children: {
            type: string
            version: number
            [k: string]: unknown
          }[]
          direction: ('ltr' | 'rtl') | null
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
          indent: number
          version: number
        }
        [k: string]: unknown
      } | null
    }
    storyIntro?: string | null
    storyContent?: {
      heading?: string | null
      story?: {
        root: {
          type: string
          children: {
            type: string
            version: number
            [k: string]: unknown
          }[]
          direction: ('ltr' | 'rtl') | null
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
          indent: number
          version: number
        }
        [k: string]: unknown
      } | null
    }
  }
  teamMembersSection?: {
    title?: string | null
    members?: (string | TeamMember)[] | null
  }
  expertsSection?: {
    title?: string | null
    experts?: (string | Expert)[] | null
    action?: string | null
  }
  opportunitiesSection?: {
    title?: string | null
    image?: (string | null) | Media
    description?: {
      root: {
        type: string
        children: {
          type: string
          version: number
          [k: string]: unknown
        }[]
        direction: ('ltr' | 'rtl') | null
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
        indent: number
        version: number
      }
      [k: string]: unknown
    } | null
    action?: string | null
    subAction?: string | null
  }
  contactSection?: {
    contactSection?: {
      title?: string | null
      contacts?:
        | {
            phone?: string | null
            id?: string | null
          }[]
        | null
      location?: string | null
      socialMediaLinks?:
        | {
            socialMediaPlatform?: ('facebook' | 'x' | 'linkedin' | 'instagram') | null
            url?: string | null
            id?: string | null
          }[]
        | null
    }
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Manage the content of your privacy policy page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: string
  title: string
  hero?: {
    headline?: string | null
    subhead?: string | null
  }
  lastUpdated?: string | null
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Manage the content of your terms and conditions page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: string
  title: string
  hero?: {
    headline?: string | null
    subhead?: string | null
  }
  lastUpdated?: string | null
  content: {
    root: {
      type: string
      children: {
        type: string
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-blogs".
 */
export interface OurBlog {
  id: string
  title?: string | null
  description?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-page".
 */
export interface QuizPage {
  id: string
  heading: string
  subtitle1?: string | null
  subtitle2?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSetion?:
    | T
    | {
        heroSectionTitle?: T
        heroSectionDescription?: T
        heroSectionImage?: T
        heroSectionAction?: T
        heroSectionHeadline?: T
        heroSectionDetails?:
          | T
          | {
              label?: T
              value?: T
              id?: T
            }
      }
  deepTmsSection?:
    | T
    | {
        title?: T
        description?: T
        action?: T
        deepTmsFeatures?:
          | T
          | {
              title?: T
              background?: T
              image?: T
              description?: T
              stampImage?: T
              id?: T
            }
      }
  mapSection?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  treatmentSection?:
    | T
    | {
        title?: T
        premaryImage?: T
        secondryImage?: T
        description?: T
        subTitle?: T
        action?: T
        featureList?:
          | T
          | {
              title?: T
              feature?: T
              id?: T
            }
        videoUrl?: T
      }
  whyChooseSection?:
    | T
    | {
        title?: T
        action?: T
        image?: T
        featuresCards?:
          | T
          | {
              featureTitle?: T
              featureDescription?: T
              featureIcon?: T
              id?: T
            }
      }
  packagesSection?:
    | T
    | {
        title?: T
        availablePackages?:
          | T
          | {
              name?: T
              price?:
                | T
                | {
                    price?: T
                    unitText?: T
                  }
              description?: T
              featureHeadline?: T
              features?:
                | T
                | {
                    title?: T
                    id?: T
                  }
              action?: T
              id?: T
            }
      }
  servicesSection?:
    | T
    | {
        title?: T
        action?: T
        cardAction?: T
      }
  expertsSection?:
    | T
    | {
        title?: T
        experts?: T
        action?: T
      }
  contactSection?:
    | T
    | {
        contactSection?:
          | T
          | {
              title?: T
              contacts?:
                | T
                | {
                    phone?: T
                    id?: T
                  }
              location?: T
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T
                    url?: T
                    id?: T
                  }
            }
      }
  quizSection?:
    | T
    | {
        quizTitle?: T
        quizDescription?: T
        quizFeatures?:
          | T
          | {
              text?: T
              id?: T
            }
        quizButtonText?: T
        quizImage?: T
      }
  testimonialSection?:
    | T
    | {
        title?: T
        testimonialSlides?: T
      }
  faqSection?:
    | T
    | {
        title?: T
        faqQuestionsAndAnswer?:
          | T
          | {
              question?: T
              answer?: T
              id?: T
            }
      }
  achievementSection?:
    | T
    | {
        title?: T
        achievements?:
          | T
          | {
              number?: T
              label?: T
              icon?: T
              id?: T
            }
      }
  partnersSection?:
    | T
    | {
        title?: T
        partners?:
          | T
          | {
              logo?: T
              id?: T
            }
      }
  blogsSection?:
    | T
    | {
        title?: T
        action?: T
        featuredBlogs?: T
      }
  webinarsSection?:
    | T
    | {
        title?: T
        description?: T
        action?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-tms_select".
 */
export interface DeepTmsSelect<T extends boolean = true> {
  deepTmsHeroSection?:
    | T
    | {
        title?: T
        description?: T
        image?: T
        videoUrl?: T
        statCards?:
          | T
          | {
              title?: T
              value?: T
              description?: T
              id?: T
            }
        action?: T
      }
  deepTmsWorkSection?:
    | T
    | {
        title?: T
        deepTmsWorkCards?:
          | T
          | {
              image?: T
              title?: T
              description?: T
              id?: T
            }
      }
  deepTmsComparisonSection?:
    | T
    | {
        title?: T
        featureParameterColumn?:
          | T
          | {
              heading?: T
              background?: T
              textColor?: T
            }
        deepTmsFeatureColumn?:
          | T
          | {
              heading?: T
              background?: T
              textColor?: T
            }
        traditionalFeatureColumn?:
          | T
          | {
              heading?: T
              background?: T
              textColor?: T
            }
        comparisonRows?:
          | T
          | {
              feature?: T
              deepTmsFeature?: T
              traditionalFeature?: T
              id?: T
            }
      }
  deepTmsEligibilitySection?:
    | T
    | {
        title?: T
        image?: T
        subTitle?: T
        eligibilityList?:
          | T
          | {
              addEligibility?: T
              id?: T
            }
        action?: T
      }
  servicesSection?:
    | T
    | {
        title?: T
        action?: T
        cardAction?: T
      }
  contactSection?:
    | T
    | {
        contactSection?:
          | T
          | {
              title?: T
              contacts?:
                | T
                | {
                    phone?: T
                    id?: T
                  }
              location?: T
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T
                    url?: T
                    id?: T
                  }
            }
      }
  faqSection?:
    | T
    | {
        title?: T
        faqQuestionsAndAnswer?:
          | T
          | {
              question?: T
              answer?: T
              id?: T
            }
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-services_select".
 */
export interface OurServicesSelect<T extends boolean = true> {
  servicesHeroSection?:
    | T
    | {
        image?: T
        title?: T
        description?: T
        action?: T
        featureCards?:
          | T
          | {
              title?: T
              description?: T
              featureImage?: T
              id?: T
            }
      }
  mainServicesSection?:
    | T
    | {
        heading?: T
        action?: T
      }
  testimonialSection?:
    | T
    | {
        title?: T
        testimonialSlides?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  contactUs?:
    | T
    | {
        title?: T
        subtitle?: T
        description?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  aboutUsHeroSection?:
    | T
    | {
        preHeader?: T
        heading?: T
        description?: T
        overlayContent?:
          | T
          | {
              overlayImage?: T
              heading?: T
              description?: T
              statistics?:
                | T
                | {
                    value?: T
                    label?: T
                    id?: T
                  }
            }
      }
  whatWeDoSection?:
    | T
    | {
        heading?: T
        description?: T
        featureCards?:
          | T
          | {
              heading?: T
              description?: T
              image?: T
              id?: T
            }
      }
  missionVisionStory?:
    | T
    | {
        purposeHeading?: T
        mission?:
          | T
          | {
              heading?: T
              description?: T
            }
        vision?:
          | T
          | {
              heading?: T
              description?: T
            }
        storyIntro?: T
        storyContent?:
          | T
          | {
              heading?: T
              story?: T
            }
      }
  teamMembersSection?:
    | T
    | {
        title?: T
        members?: T
      }
  expertsSection?:
    | T
    | {
        title?: T
        experts?: T
        action?: T
      }
  opportunitiesSection?:
    | T
    | {
        title?: T
        image?: T
        description?: T
        action?: T
        subAction?: T
      }
  contactSection?:
    | T
    | {
        contactSection?:
          | T
          | {
              title?: T
              contacts?:
                | T
                | {
                    phone?: T
                    id?: T
                  }
              location?: T
              socialMediaLinks?:
                | T
                | {
                    socialMediaPlatform?: T
                    url?: T
                    id?: T
                  }
            }
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  title?: T
  hero?:
    | T
    | {
        headline?: T
        subhead?: T
      }
  lastUpdated?: T
  content?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  title?: T
  hero?:
    | T
    | {
        headline?: T
        subhead?: T
      }
  lastUpdated?: T
  content?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-blogs_select".
 */
export interface OurBlogsSelect<T extends boolean = true> {
  title?: T
  description?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-page_select".
 */
export interface QuizPageSelect<T extends boolean = true> {
  heading?: T
  subtitle1?: T
  subtitle2?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null
    format?: ('csv' | 'json') | null
    limit?: number | null
    page?: number | null
    sort?: string | null
    sortOrder?: ('asc' | 'desc') | null
    drafts?: ('yes' | 'no') | null
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null
    fields?: string[] | null
    collectionSlug: string
    where?:
      | {
          [k: string]: unknown
        }
      | unknown[]
      | string
      | number
      | boolean
      | null
    user?: string | null
    userCollection?: string | null
    exportsCollection?: string | null
  }
  output?: unknown
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
